services:
    victoire_core.widget_simplecontactform_content_resolver:
        class: Victoire\Widget\SimpleContactFormBundle\Resolver\WidgetSimpleContactFormResolver
        arguments:
            - "@form.factory"
            - "@router"
            - %victoire_widget_simple_contact_form.entity_class%
            - %victoire_widget_simple_contact_form.form_class%
            - %victoire_widget_simple_contact_form.form_action_route%
        parent: victoire_widget.base_widget_content_resolver
        tags:
            - { name: victoire_widget.widget_content_resolver, alias: SimpleContactForm }
    #alias to the entity
    victoire.widget.simplecontactform:
        class: Victoire\Widget\SimpleContactFormBundle\Entity\WidgetSimpleContactForm

    #alias to the form
    victoire.widget.form.simplecontactform:
        class: Victoire\Widget\SimpleContactFormBundle\Form\WidgetSimpleContactFormType
        tags:
            - { name: form.type , alias: victoire_widget_form_simplecontactform }
